version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.3-native-mt
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-android
    versions:
    - 1.4.3-native-mt
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.3
  - dependency-name: com.diffplug.spotless
    versions:
    - 5.11.0
  - dependency-name: app.redwarp.gif:decoder
    versions:
    - 0.4.0
  - dependency-name: app.redwarp.gif:android-drawable
    versions:
    - 0.4.0
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk7
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.31
